corpus/historical/justice_policing/compas_2016.yaml
corpus/historical/justice_policing/predpol_lapd_2019.yaml
corpus/historical/surveillance_privacy/cambridge_analytica_2018.yaml
corpus/historical/surveillance_privacy/clearview_ai_2022.yaml
corpus/historical/employment/amazon_recruiting_2018.yaml
corpus/historical/employment/hirevue_2019.yaml
corpus/historical/welfare_social/netherlands_welfare_2020.yaml
corpus/historical/welfare_social/robodebt_au_2015_2023.yaml
corpus/historical/platforms_pricing/uber_surge_emergencies_2014.yaml
