# configs/mesh.yaml
# Backend: "http" (prod) ou "git" (boîte aux lettres via branche Git)
backend: "http"          # passe à "git" si tu utilises le mode mailbox
node_id: "node-alpha"    # unique par nœud

http:
  shared_token: "CHANGE_ME_SECRET"   # même secret sur tous les nœuds
  peers:
    - name: "node-bravo"
      url: "https://bravo.example.com/api"
    # - name: "node-charlie"
    #   url: "https://charlie.example.com/api"

git:
  repo_url: "https://github.com/DeepKang-Labs/Sigma-Lab-Framework.git"
  branch: "mesh-mailbox"
  author_name: "sigma-bot"
  author_email: "sigma-bot@deepkang.labs"
