# configs/mesh.yaml
# Select backend: "http" (real peers) or "git" (CI/mailbox)
backend: "git"         # change to "http" when you deploy servers
node_id: "node-alpha"  # unique per node

http:
  shared_token: "CHANGE_ME_SECRET"  # same secret on all peers
  peers:
    - name: "node-bravo"
      url: "https://YOUR_NODE_BRAVO_HOST/api"   # e.g., http(s)://host:port/api
    # - name: "node-charlie"
    #   url: "https://YOUR_NODE_CHARLIE_HOST/api"

git:
  repo_url: "https://github.com/DeepKang-Labs/Sigma-Lab-Framework.git"
  branch: "mesh-mailbox"
  author_name: "sigma-bot"
  author_email: "sigma-bot@deepkang.labs"
