name: ci-docker

on:
  push:
    branches: [ "main" ]
    paths:
      - "Dockerfile"
      - "docker/**"
      - "scripts/**"
      - "configs/**"
      - "requirements.txt"
      - ".github/workflows/docker_ci.yml"
  workflow_dispatch: {}

jobs:
  build-and-smoke:
    runs-on: ubuntu-latest

    # IMPORTANT: autoriser l’écriture sur GHCR
    permissions:
      contents: read
      packages: write

    env:
      # Mise en minuscules pour GHCR
      IMAGE_OWNER: ${{ toLower(github.repository_owner) }}
      IMAGE_NAME: ghcr.io/${{ toLower(github.repository_owner) }}/sigma
      ARTIFACTS_ROOT: artifacts

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline

      - name: Prepare artifacts folders
        run: |
          rm -rf "$ARTIFACTS_ROOT"
          mkdir -p "$ARTIFACTS_ROOT/heartbeat" \
                   "$ARTIFACTS_ROOT/mesh/inbox" \
                   "$ARTIFACTS_ROOT/mesh/outbox" \
                   "$ARTIFACTS_ROOT/mesh/archive" \
                   "$ARTIFACTS_ROOT/model"

      - name: Smoke • node
        run: |
          docker run --rm \
            -e MODE=node \
            -e ARTIFACTS_ROOT=/data/artifacts \
            -v "${{ github.workspace }}/artifacts:/data/artifacts" \
            "${{ env.IMAGE_NAME }}:latest"

      - name: Smoke • federate
        run: |
          docker run --rm \
            -e MODE=federate \
            -e ARTIFACTS_ROOT=/data/artifacts \
            -v "${{ github.workspace }}/artifacts:/data/artifacts" \
            "${{ env.IMAGE_NAME }}:latest"

      - name: Smoke • apply
        run: |
          docker run --rm \
            -e MODE=apply \
            -e ARTIFACTS_ROOT=/data/artifacts \
            -v "${{ github.workspace }}/artifacts:/data/artifacts" \
            "${{ env.IMAGE_NAME }}:latest"

      - name: Upload artifacts (snapshot)
        uses: actions/upload-artifact@v4
        with:
          name: sigma_artifacts_${{ github.run_id }}
          path: artifacts
          if-no-files-found: warn
          retention-days: 7
