name: nightly

on:
  schedule:
    - cron: "0 3 * * *" # every day at 03:00 UTC
  workflow_dispatch:

jobs:
  nightly-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest simpleeval

      - name: Create required folders
        run: |
          mkdir -p pilots/validation_logs
          mkdir -p discovery

      - name: Create demo discovery data (safe fallback)
        shell: bash
        run: |
          if [ ! -f discovery/decision_mapper.yaml ]; then
            python - <<'PY'
from pathlib import Path
content = """version: "1.0"
discovery_date: "2025-10-25"
decision_points:
  - decision_id: "dp_demo_ci"
    description: "CI demo decision for nightly"
    stakeholders: ["end_users", "core_devs"]
    governance_dimensions:
      technical_complexity: 5
      economic_impact: 4
      user_experience_impact: 6
      security_implications: 3
      current_pain_level: 5
"""
Path("discovery").mkdir(parents=True, exist_ok=True)
Path("discovery/decision_mapper.yaml").write_text(content, encoding="utf-8")
print("Wrote discovery/decision_mapper.yaml")
PY
          fi

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Run unit tests (core + bridge)
        run: python -m pytest -q

      - name: Bridge • validate-only (Skywire)
        run: |
          PYTHONPATH=$PWD python -m network_bridge.run_network_integrated \
            --network skywire \
            --discovery ./discovery \
            --mappings ./network_bridge/mappings_skywire.yaml \
            --config ./sigma_config_placeholder.yaml \
            --out ./pilots/validation_logs/skywire_validate_only.json \
            --validate-only \
            --formula-eval auto

      - name: Bridge • validate-only (Fiber)
        run: |
          PYTHONPATH=$PWD python -m network_bridge.run_network_integrated \
            --network fiber \
            --discovery ./discovery \
            --mappings ./network_bridge/mappings_fiber.yaml \
            --config ./sigma_config_placeholder.yaml \
            --out ./pilots/validation_logs/fiber_validate_only.json \
            --validate-only \
            --formula-eval auto

      - name: Tools • mesh_memory_append
        run: |
          PYTHONPATH=$PWD python -m tools.mesh_memory_append \
            --report ./pilots/validation_logs/mesh_memory_report.json

      - name: Tools • priority_matrix_from_mappings
        run: |
          PYTHONPATH=$PWD python -m tools.priority_matrix_from_mappings \
            --mappings ./network_bridge/mappings_skywire.yaml \
            --out ./pilots/validation_logs/priority_matrix_report.json
