name: nightly-validate

on:
  schedule:
    - cron: '23 2 * * *'   # tous les jours ~02:23 UTC
  workflow_dispatch:

jobs:
  nightly:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest

      - name: Create required folders
        run: |
          mkdir -p pilots/validation_logs
          mkdir -p discovery
          mkdir -p pilots/mesh_memory
          mkdir -p tools

      - name: Create demo discovery data (safe fallback)
        shell: bash
        run: |
          if [ ! -f discovery/decision_mapper.yaml ]; then
            cat > discovery/decision_mapper.yaml <<'YAML'
version: "1.0"
discovery_date: "2025-10-25"
decision_points:
  - decision_id: "dp_demo_ci"
    description: "CI demo decision for nightly"
    stakeholders: ["end_users","core_devs"]
    governance_dimensions:
      technical_complexity: 5
      economic_impact: 4
      user_experience_impact: 6
      security_implications: 3
    current_pain_level: 5
YAML
          fi

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Unit tests (core + bridge)
        run: python -m pytest -q

      - name: Bridge • validate-only (Skywire)
        run: |
          python -m network_bridge.run_network_integrated \
            --network skywire \
            --discovery ./discovery \
            --mappings ./network_bridge/mappings_skywire.yaml \
            --config ./sigma_config_placeholder.yaml \
            --out ./pilots/validation_logs/skywire_validate_only.json \
            --validate-only \
            --formula-eval auto \
            --pretty

      - name: Bridge • validate-only (Fiber)
        run: |
          python -m network_bridge.run_network_integrated \
            --network fiber \
            --discovery ./discovery \
            --mappings ./network_bridge/mappings_fiber.yaml \
            --config ./sigma_config_placeholder.yaml \
            --out ./pilots/validation_logs/fiber_validate_only.json \
            --validate-only \
            --formula-eval auto \
            --pretty

      - name: Mesh Memory • append both reports
        run: |
          python tools/mesh_memory_append.py \
            --report pilots/validation_logs/skywire_validate_only.json \
            --memory pilots/mesh_memory/mesh_memory.jsonl || true
          python tools/mesh_memory_append.py \
            --report pilots/validation_logs/fiber_validate_only.json \
            --memory pilots/mesh_memory/mesh_memory.jsonl || true

      - name: Priority Matrix • from discovery
        run: |
          python tools/priority_matrix_from_discovery.py \
            --in discovery/decision_mapper.yaml \
            --out pilots/validation_logs/governance_priority_matrix.csv

      - name: Upload nightly artifacts (7 days)
        uses: actions/upload-artifact@v4
        with:
          name: nightly-artifacts
          path: |
            pilots/validation_logs/*.json
            pilots/validation_logs/*.csv
            pilots/mesh_memory/*.jsonl
          retention-days: 7
