name: nightly

on:
  schedule:
    - cron: "0 2 * * *"   # 02:00 UTC daily
  workflow_dispatch:

jobs:
  nightly:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Ensure CI tools are present
          pip install pytest simpleeval

      - name: Create required folders
        run: |
          mkdir -p pilots/validation_logs
          mkdir -p discovery

      - name: Create demo discovery data (safe fallback)
        shell: bash
        run: |
          if [ ! -f discovery/decision_mapper.yaml ]; then
            cat > discovery/decision_mapper.yaml <<'YAML'
version: "1.0"
discovery_date: "2025-10-25"
decision_points:
  - decision_id: "dp_demo_ci"
    description: "CI demo decision for nightly"
    stakeholders: ["end_users","core_devs"]
    governance_dimensions:
      technical_complexity: 5
      economic_impact: 4
      user_experience_impact: 6
      security_implications: 3
    current_pain_level: 5
YAML
          fi

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Run unit tests (core + bridge)
        run: python -m pytest -q

      # ---- Bridge validate-only (Skywire)
      - name: Bridge • validate-only (Skywire)
        run: |
          python -m network_bridge.run_network_integrated \
            --network skywire \
            --discovery ./discovery \
            --mappings ./network_bridge/mappings_skywire.yaml \
            --config ./sigma_config_placeholder.yaml \
            --out ./pilots/validation_logs/skywire_validate_only.json \
            --validate-only \
            --formula-eval auto \
            --pretty

      # ---- Bridge validate-only (Fiber)
      - name: Bridge • validate-only (Fiber)
        run: |
          python -m network_bridge.run_network_integrated \
            --network fiber \
            --discovery ./discovery \
            --mappings ./network_bridge/mappings_fiber.yaml \
            --config ./sigma_config_placeholder.yaml \
            --out ./pilots/validation_logs/fiber_validate_only.json \
            --validate-only \
            --formula-eval auto \
            --pretty

      # ---- Tools: Mesh Memory append
      - name: Tools • mesh_memory_append
        run: |
          python -m tools.mesh_memory_append \
            --input ./pilots/validation_logs \
            --output ./pilots/validation_logs/mesh_memory.jsonl

      # ---- Tools: Priority Matrix from discovery
      - name: Tools • priority_matrix_from_discovery
        run: |
          python -m tools.priority_matrix_from_discovery \
            --discovery ./discovery/decision_mapper.yaml \
            --output ./pilots/validation_logs/priority_matrix.csv

      - name: Upload nightly artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nightly-artifacts
          path: |
            pilots/validation_logs/*.json
            pilots/validation_logs/*.jsonl
            pilots/validation_logs/*.csv
