name: bridge-smoke (manual)

on:
  workflow_dispatch: {}

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Demo discovery
        run: |
          mkdir -p .tmp reports/smoke
          printf "036a_dummyA\n047b_dummyB\n" > .tmp/visors_pks.txt
          echo "PYTHONPATH=$PWD" >> "$GITHUB_ENV"

      - name: Bridge • validate-only (Skywire)
        run: |
          python -m network_bridge.run_network_integrated \
            --network skywire \
            --discovery .tmp/visors_pks.txt \
            --out reports/smoke/skywire_validation.json \
            --also-md

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: bridge_smoke_${{ github.run_id }}
          path: reports/smoke
          if-no-files-found: error
          retention-days: 7
