name: SigmaLab Smoke Test

on:
  push:
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install numpy pyyaml

      - name: Import adapter & core (smoke)
        run: |
          python - <<'PY'
          try:
              from engine.sigma_lab_v421 import SigmaLab, SigmaConfig
              print("✅ Adapter import OK:", SigmaLab, SigmaConfig)
          except Exception as e:
              print("❌ Adapter import FAILED")
              raise
          PY
