name: skywire-report

on:
  schedule:
    - cron: "10 6 * * *"   # tous les jours 06:10 UTC (après vitals)
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history, with token)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install pandas matplotlib

      - name: Build Skywire Vital Report
        run: |
          python scripts/skywire_vital_report.py

      - name: Publish 'reports/latest' alias
        shell: bash
        run: |
          set -euo pipefail
          LATEST_DIR="reports/latest"
          rm -rf "$LATEST_DIR"
          mkdir -p "$LATEST_DIR"
          LAST_DIR=$(ls -1d reports/20*/ 2>/dev/null | sort | tail -n1 || true)
          if [ -n "$LAST_DIR" ]; then
            cp -r "$LAST_DIR"* "$LATEST_DIR"/
          fi

      - name: Commit & push (rebase-safe)
        shell: bash
        run: |
          set -euo pipefail
          git config user.name  "sigma-bot"
          git config user.email "actions@users.noreply.github.com"

          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "feat(report): publish daily artifacts + latest alias"
          fi

          git fetch origin main
          git pull --rebase origin main || (git rebase --abort && git pull --no-rebase origin main)

          git push
