name: smoke

on:
  push:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Ensure pytest is available for unit tests
          pip install pytest

      - name: Create required folders
        run: |
          mkdir -p discovery
          mkdir -p pilots/validation_logs
          # keep folder tracked
          touch pilots/validation_logs/.gitkeep

      - name: Create demo discovery data (safe fallback)
        run: |
          cat > discovery/decision_mapper.yaml << 'YAML'
          version: "1.0"
          discovery_date: "2025-10-25"
          decision_points: []
          YAML

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Run unit tests (bridge)
        run: |
          python -m pytest -q

      - name: Bridge • validate-only (Skywire)
      # Produces a JSON report without executing Sigma-Lab
        run: |
          python network_bridge/run_network_integrated.py \
            --network skywire \
            --discovery ./discovery \
            --mappings ./network_bridge/mappings_skywire.yaml \
            --config ./sigma_config_placeholder.yaml \
            --out ./pilots/validation_logs/skywire_validate_only.json \
            --validate-only \
            --formula-eval auto \
            --pretty

      - name: Bridge • validate-only (Fiber)
        run: |
          python network_bridge/run_network_integrated.py \
            --network fiber \
            --discovery ./discovery \
            --mappings ./network_bridge/mappings_fiber.yaml \
            --config ./sigma_config_placeholder.yaml \
            --out ./pilots/validation_logs/fiber_validate_only.json \
            --validate-only \
            --formula-eval auto \
            --pretty

      - name: Upload validate-only reports
        uses: actions/upload-artifact@v4
        with:
          name: validate-only-reports
          path: |
            pilots/validation_logs/skywire_validate_only.json
            pilots/validation_logs/fiber_validate_only.json
