name: smoke

on:
  push:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # pytest explicit to avoid missing dev-dep
          pip install pytest

      - name: Create required folders
        run: |
          mkdir -p pilots/validation_logs
          mkdir -p discovery

      - name: Create demo discovery data (safe fallback)
        run: |
          if [ ! -f discovery/decision_mapper.yaml ]; then
            echo "version: '1.0'
discovery_date: '2025-10-25'
decision_points:
  - decision_id: 'dp_demo_ci'
    description: 'CI demo decision for smoke'
    stakeholders: ['end_users','core_devs']
    governance_dimensions:
      technical_complexity: 5
      economic_impact: 4
      user_experience_impact: 6
      security_implications: 3
    current_pain_level: 5" > discovery/decision_mapper.yaml
          fi

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Run unit tests (bridge + core)
        run: python -m pytest -q

      # --- Network Bridge validate-only (module invocation for robust imports)
      - name: Bridge • validate-only (Skywire)
        run: |
          python -m network_bridge.run_network_integrated \
            --network skywire \
            --discovery ./discovery \
            --mappings ./network_bridge/mappings_skywire.yaml \
            --config ./sigma_config_placeholder.yaml \
            --out ./pilots/validation_logs/skywire_validate_only.json \
            --validate-only \
            --formula-eval auto \
            --pretty

      - name: Bridge • validate-only (Fiber)
        run: |
          python -m network_bridge.run_network_integrated \
            --network fiber \
            --discovery ./discovery \
            --mappings ./network_bridge/mappings_fiber.yaml \
            --config ./sigma_config_placeholder.yaml \
            --out ./pilots/validation_logs/fiber_validate_only.json \
            --validate-only \
            --formula-eval auto \
            --pretty

      - name: Upload validate-only reports
        uses: actions/upload-artifact@v4
        with:
          name: validate-only-reports
          path: pilots/validation_logs/*.json
